### ISSUE TITLE
Windows Phone 8.1 client. KeenClient.AddEventAsync crashes app in airplane mode.

### ISSUE THREAD

**Issue by vadim-tsedrik** [keenlabs/keen-sdk-net#19]
Hi there. 
When i set phone to the airplane mode keenClient crashes application with unhandled exception.
Call stack if it helps:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
  at unknown location

Aggregated Exception [0]: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Keen.Core.KeenClient.<AddEventAsync>d__18.MoveNext()

**Comment by davidknaack** [comment]
Hi! Thanks for the report! I'll take a look and let you know what I find.

**Comment by iturpablo** [comment]
Hi, 
I am having troubles with your library with the same error in the version 0.3.11, do you have any information about it? 

Thank you soo much 

same error:
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException`Newtonsoft.Json.Linq.JObject' does not contain a definition for `SelectToken'
Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
Microsoft.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
Keen.Core.KeenClient.<AddEventAsync>d__18.MoveNext()
